### ISSUE TITLE
Import statements

### ISSUE THREAD

**Issue by jackyyylewis** [mccallum-sgd/assign2#3]
Whilst browsing the import statements of SeanPanel I accidentally deleted them somehow someway. But everything seemed to compile fine when I re-imported what I think I deleted. Just to let you all know.

**Comment by mccallum-sgd** [comment]
Yeah I think eclipse just automatically readded them with wildcards, I fixed it [here](https://github.com/mccallum-sgd/assign2/commit/3f71b30fcf428a47404b093c2726d0c6a2187c2b#diff-867a7f5578d9c1881e46cba874e7a5e9).
